### ISSUE TITLE
A few of the modules with large image to left or right text not positioning correctly and is behind image in some cases

### ISSUE THREAD

**Issue by andyError** [andyError/noc_templates#2]

**Comment by cpc74** [comment]
Andy,
On the front page the full screen hero background image is not covering the full screen width -
![fp-screenshot](https://user-images.githubusercontent.com/54936771/64333763-29eba600-cfcf-11e9-8bc3-d56dd5921f1f.jpg)

**Comment by cpc74** [comment]
Some of the image and header modules text runs behind image - 
![module-with-text-behind-image](https://user-images.githubusercontent.com/54936771/64334029-a1b9d080-cfcf-11e9-8222-be16d56f4f49.jpg)

**Comment by cpc74** [comment]
Lander page header image not rendering correctly - 
![lander-header-img-issue](https://user-images.githubusercontent.com/54936771/64334227-0412d100-cfd0-11e9-8c1e-868368f77998.jpg)

**Comment by cpc74** [comment]
Another example -
![lander-header-img-issue2](https://user-images.githubusercontent.com/54936771/64334537-a03cd800-cfd0-11e9-83f0-2470c07e4b5a.jpg)

**Comment by cpc74** [comment]
Modules with text behind image on left and right - 
![module-with-text-behind-image2](https://user-images.githubusercontent.com/54936771/64335329-7b496480-cfd2-11e9-9f58-37982c7ac51d.jpg)

**Comment by andyError** [comment]
About:

_On the front page the full screen hero background image is not covering the full screen width_

This is intentional. The site has a max width of 1680px, this is because of how difficult it would be to chose and crop images that would work on really wide screens - TVs for examples.

**Comment by cpc74** [comment]
> About:
> On the front page the full screen hero background image is not covering the full screen width
> This is intentional. The site has a max width of 1680px, this is because of how difficult it would be to chose and crop images that would work on really wide screens - TVs for examples.

Okay so it is going to be different from the BODC front page which has full screen width for all devices? We should maybe discuss this internally.

**Comment by andyError** [comment]
Interesting, I thought the fixed width was in line with BODC but you're right. It doesn't matter so much on BODC because the image is set and it's an abstract one BUT I'd suggest fixing the width on BODC for consistency.

**Comment by andyError** [comment]
OK I've fixed the issues above, should be all good in the next drop of code :)

**Comment by andyError** [comment]
I’m going to close, these issues have all been addressed.
