### ISSUE TITLE
Responsive design issues

### ISSUE THREAD

**Issue by cpc74** [andyError/noc_templates#4]
Andy, a few questions and issues I have spotted whilst doing some testing with the templates on different view-ports and devices - 

Footer is still 3 cols on phones and not stacked. Is this intentional?

![phone-footer-3-cols fw](https://user-images.githubusercontent.com/54936771/64775667-92e29900-d54e-11e9-8d3a-a22a284927f6.png)

**Comment by cpc74** [comment]
On phones the header text on a hero images go further down than the image and then can't be read and push content down leaving a gap -

![phone-hero-header-text-issue fw](https://user-images.githubusercontent.com/54936771/64775849-fcfb3e00-d54e-11e9-8d1e-79f0f0111279.png)

**Comment by cpc74** [comment]
A content page on a phone the left-hand-menu (or at least some of it is still showing) - 

![phone-hero-header-left-hand-menu-issue fw](https://user-images.githubusercontent.com/54936771/64776082-7430d200-d54f-11e9-9273-768ce165c34b.png)

**Comment by andyError** [comment]
There's still quite a lot of responsive to do. Quite honestly, I don't think it's really ready for you to be testing on devices. During the last sprint, I created responsive styles for the majority of the modules on the all-modules template, but I have not address the headers or footers yet. Some styles may persist from the earlier BODC styles.

**Comment by cpc74** [comment]
Okay Andy I will leave off adding anymore to here till you think it is ready for further testing. I understand you are still working on the details and especially from a responsive perspective. 
I thought I'd put them in here so we have a record of them but maybe be better to wait till you think more ready.

**Comment by andyError** [comment]
It's up to you really if you want to add a few issues to keep track of things, I just wanted to make that clear ^ so you're not finding lots of unfinished bits and getting frustrated :)

**Comment by cpc74** [comment]
It will just be annoying if I keep pointing out things and you are thinking – ‘yes I know, not yet done all of that I’ve told you’.
I will keep a list and we can review it later.

**Comment by andyError** [comment]
Going to close this, these issues are fixed, and future issues would be best off in individual tickets.
