### ISSUE TITLE
Menu doubling up on phone/tablet, hamburger icon

### ISSUE THREAD

**Issue by cpc74** [andyError/noc_templates#5]
If a page has a secondary menu on the left in the header, and you then reduce display till hamburger icon then the menu doubles up and won't collapse correctly or shut down (no 'X' in top right) - 

![phone-menu-doubling-up fw](https://user-images.githubusercontent.com/54936771/66655476-07832300-ec34-11e9-9409-40d3fcfd4b2f.png)

No 'X' to close if screen size is increased above 1150 with menu open

![responsive-menu-noexit-after-1150 fw](https://user-images.githubusercontent.com/54936771/66656846-add02800-ec36-11e9-8e5d-b191da23f0ff.png)

**Comment by andyError** [comment]
Doubling issue was fixed today, and will be included in next drop. I’ll fix the menu to auto hide if opened in a small browser which is subsequently widened.

**Comment by andyError** [comment]
This is now fixed. I've just made sure that the close icon is always present if the menu is.
