### ISSUE TITLE
Footer stacking between 481-767 (approx)

### ISSUE THREAD

**Issue by cpc74** [andyError/noc_templates#6]
Footer stacks to 1 col up to 480 and then two cols till 767 and then 3 cols 767 up. Is it meant to stack to two cols between 480 - 767? It looks okay and can live with but just checking it is meant to look this way - 

![footer-stack-correct-481-767 fw](https://user-images.githubusercontent.com/54936771/66656229-7e6ceb80-ec35-11e9-9c47-9c7f191131fe.png)

**Comment by andyError** [comment]
Yes, that’s intentional. It adapts to the space available.
