### ISSUE TITLE
Header hero image issue with class m-index-hero

### ISSUE THREAD

**Issue by cpc74** [andyError/noc_templates#7]
The header hero image is rendering wrong on any page that calls class 'm-index-hero'. Examples are - 'index list', 'search results' and 'project list'. May just be swap to class 'm-content-hero'.

![hero-image-m-index fw](https://user-images.githubusercontent.com/54936771/66657990-7c585c00-ec38-11e9-88a0-03665df1df6e.png)

**Comment by andyError** [comment]
This is now fixed, stick with .m-index.hero.
