### ISSUE TITLE
Are border sizes correct and intentional at various break points?

### ISSUE THREAD

**Issue by cpc74** [andyError/noc_templates#8]
When viewed wide on a desktop borders are 100px - 

![border-100-wide fw](https://user-images.githubusercontent.com/54936771/66659281-1ae5bc80-ec3b-11e9-857b-8869aaf784fb.png)

Then when between 770 -1350 (approx) border is 40px -

![border-40-between-770-1350 fw](https://user-images.githubusercontent.com/54936771/66659342-38b32180-ec3b-11e9-9109-26070d5c7fb4.png)

Then when less than 770 the borders jump to 150px. Is this correct and intended?

![border-150-less-than770 fw](https://user-images.githubusercontent.com/54936771/66659406-5aaca400-ec3b-11e9-9fb4-6fb2b5e0425f.png)

**Comment by andyError** [comment]
Yes, that is expected. The spacing between elements is set based on things like text line lengths, or taking advantage of screen estate on smaller devices.
